# --------------------------------------- 
# Module: https
# Adds HTTPS protocol support to the TLS(SSL) Connector.
# --------------------------------------- 
--modules=https

# HTTP port to listen on
https.port=${HTTPS_PORT}
# HTTPS idle timeout in milliseconds
https.timeout=30000
