---
services:
  geoserver:
    container_name: geoserver
    image: allfab/geoserver-ecw:latest
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./geoserver/config:/app/geoserver/config
      - ./geoserver/data/raster:/app/geoserver/data/raster
      - ./geoserver/data/vector:/app/geoserver/data/vector
      - ./geoserver/logs:/app/geoserver/logs
      - ./geoserver/gwc/config:/app/geoserver/gwc/config
      - ./geoserver/gwc/cache:/app/geoserver/gwc/cache
      - ./geoserver/jks/keystore:/srv/jetty/geoserver-base/etc/keystore
      - ./geoserver/additional_extensions:/app/geoserver/additional_extensions
    environment:
      - GEOSERVER_CSRF_WHITELIST=example.org,*.example.org
      - HTTPS_ENABLED=true
      - HTTPS_KEYSTORE_FILE=etc/keystore
      - HTTPS_KEYSTORE_PASSWORD=password
      # - GEOSERVER_ADMIN_USER=admindemo
      # - GEOSERVER_ADMIN_PASSWORD=demodemo
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,ysld,dxf      
    networks:
      - geoserver

networks:
  geoserver:
    name: geoserver
    driver: bridge
