# Module: ssl
--module=ssl
jetty.ssl.port=8443

## Set the demonstration passwords.
## Note that OBF passwords are not secure, just protected from casual observation
## See http://www.eclipse.org/jetty/documentation/current/configuring-security-secure-passwords.html
#cd /srv/jetty
#java -cp lib/jetty-util-9.4.30.v20200611.jar org.eclipse.jetty.util.security.Password password
jetty.sslContext.keyStorePath=etc/keystore
jetty.sslContext.keyStorePassword=password
; jetty.sslContext.keyManagerPassword=OBF:1hgc1jfw1axf1abe1abo1awb1jde1heq
; jetty.sslContext.trustStorePath=etc/keystore
; jetty.sslContext.trustStorePassword=OBF:1vn21ugu1saj1v9i1v941sar1ugw1vo0