when:
  - event: push
    branch: main

steps:
  - name: Build GEOSERVER-ECW Docker Image
    image: woodpeckerci/plugin-docker-buildx:latest
    commands:
      - docker build -f ./Dockerfile --no-cache=true --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t allfab/geoserver-ecw:latest -t allfab/geoserver-ecw:3.0.0 -t allfab/geoserver-ecw:3.0.0-13.6-slim .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
  - name: Push GEOSERVER-ECW Docker Image
    image: woodpeckerci/plugin-docker-buildx:latest
    commands:
      - docker login docker.io --username=allfab -p $VAULT_DOCKERHUB_PASS
      - docker push --all-tags allfab/geoserver-ecw
      - docker rmi --force $(docker images -q allfab/geoserver-ecw)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VAULT_DOCKERHUB_PASS:
        from_secret: VAULT_DOCKERHUB_PASS

  - name: NTFY Notification ON SUCCESS
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url: https://ntfy.allfabox.fr/woodpecker-alerts
      token:
        from_secret: VAULT_NTFY_TOKEN
      title: "✅ WOODPECKER CI | ${CI_REPO_NAME} | PIPELINE #${CI_PIPELINE_NUMBER}"
      priority: default
      click: ${CI_PIPELINE_URL}
      icon: https://woodpecker-ci.org/img/logo.svg
      tags: robot,${CI_REPO_NAME}
      message: |
        Déploiement réussi sur le dépôt ${CI_REPO_NAME}
        Référence du commit : ${CI_COMMIT_MESSAGE}
        Réalisé par ${CI_COMMIT_AUTHOR} sur la branche ${CI_COMMIT_BRANCH}

  - name: NTFY Notification ON FAILURE
    image: codeberg.org/l-x/woodpecker-ntfy
    when:
      status:
        - failure
    settings:
      url: https://ntfy.allfabox.fr/woodpecker-alerts
      token:
        from_secret: VAULT_NTFY_TOKEN
      title: "❌ WOODPECKER CI | ${CI_REPO_NAME} | PIPELINE #${CI_PIPELINE_NUMBER}"
      priority: high
      click: ${CI_PIPELINE_URL}
      icon: https://woodpecker-ci.org/img/logo.svg
      tags: robot,${CI_REPO_NAME}
      message: |
        Déploiement échoué sur le dépôt ${CI_REPO_NAME}
        Référence du commit : ${CI_COMMIT_MESSAGE}
        Réalisé par ${CI_COMMIT_AUTHOR} sur la branche ${CI_COMMIT_BRANCH}