when:
  - event: push
    branch: main

steps:
  - name: Build GDAL-ECW Docker Image
    image: woodpeckerci/plugin-docker-buildx:latest
    commands:
      - docker build -f ./Dockerfile --no-cache=true --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t allfab/gdal-ecw:3.10.1 .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: ntfy
    image: codeberg.org/l-x/woodpecker-ntfy
    when:
      - event: push
    settings:
        url: https://ntfy.allfabox.fr/woodpecker-alerts
        # token:
            # from_secret: your-super-secret-ntfy-access-token
        title: Commit by ${CI_COMMIT_AUTHOR} on ${CI_COMMIT_BRANCH}
        priority: high
        # actions: "view, Open portal, https://home.nest.com/, clear=true; http, Turn down, https://api.nest.com/, body='{\"temperature\": 65}'"
        click: https://forgejo.allfabox.fr
        icon: https://woodpecker-ci.org/img/logo.svg
        tags: robot,${CI_REPO_NAME}
        message: ${CI_COMMIT_MESSAGE}